export {default as Homepage} from './Homepage'
export {default as Registerpage} from './Registerpage'
export {default as Loginpage} from './Loginpage'
export {default as Single} from './Single'
export {default as Createpage} from './Createpage'
export {default as Settingspage} from './Settingspage'